//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DonHang = new HashSet<DonHang>();
        }

        [DisplayName("Tên đăng nhập")]
        public string username { get; set; }
        [DisplayName("Họ và tên")]
        public string hoTen { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Số điện thoại")]
        public string sdt { get; set; }
        [DisplayName("Mật khẩu")]
        public string matkhau { get; set; }
        [DisplayName("Quyền user")]
        public int roleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
